---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.16
platforms:
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-8.9
  run_list:
  - recipe[apt]
- name: debian-9.2
  run_list:
  - recipe[apt]
- name: centos-6.9
- name: centos-7.4

verifier:
  name: inspec

suites:
- name: default
  run_list: ['recipe[bind::default]']
- name: resources
  run_list: ['recipe[bind_test]']
- name: chroot
  excludes:
    - ubuntu-16.04
  run_list:
    - recipe[bind_test::chroot]
- name: views
  includes:
    - centos-6.9
  run_list:
    - recipe[bind_test::views]
- name: logging
  includes:
    - centos-6.9
  run_list:
    - recipe[bind_test::logging]
- name: linked-zones
  includes:
    - ubuntu-16.04
    - debian-9.2
  run_list:
    - recipe[bind_test::linked_zones]
